version: '3.9'

services:
  nginx:    
    build: ./docker/nginx/
    ports:  
      - 80:80  
    links:  
      - php  
    volumes_from:  
      - app-data  

  php:    
    build: ./docker/php/
    expose:  
      - 9000  
    links:  
      - db  
    volumes_from:  
      - app-data  

  app-data:    
    image: php:8.1-fpm  
    volumes:  
      - .:/var/www/html/
    command: "true"  

  db:    
    image: mariadb 
    ports:
      - 3306:3306
    volumes_from:  
      - db-data  
    environment:  
      MYSQL_ROOT_PASSWORD: secret  
      MYSQL_DATABASE: bdb  
      MYSQL_USER: bdb  
      MYSQL_PASSWORD: password  
      MAX_ALLOWED_PACKET: 1073741824
    volumes:
      - ./docker/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./docker/db/01-init-sql-script.sql:/tmp/sql/01-init-sql-script.sql

  db-data:    
    image: mariadb
    volumes:  
      - /var/lib/mysql
    command: "true" 
